### ISSUE TITLE
[Question] Better Support & Stability

### ISSUE THREAD

**Issue by Mushoz** [dmy3k/auto-power-profile#5]
The Readme points out that this is a fork of the power-profile-switcher extension. It notes that it aims to provide better support and stability. Would you mind explaining what exactly is this doing differently or better than the project it was forked from? I am using the original project right now, and I was wondering if it's worth for me to switch over.

My main gripe with the original, is that it will automatically overwrite the values after you make a switch manually. For example, I use the extension to automatically switch to powersave on battery. However, sometimes better performance is desired, and I then try to manually set it to balanced or even performance. However, the extension will then automatically switch it back to powersave. Ideally it should only set the configured profiles upon connecting to AC or disconnecting from AC. Any manual changes thereafter should stick.

Is this fork behaving better in that regard? I see that you originally had a PR to implement this in the original extension here: https://github.com/eliapasquali/power-profile-switcher/pull/26

But you ended up closing it. Was there any reason why it was closed? And am I correct to assume that this is included in this version of the extension? Thank you very much in advance for all the information!

**Comment by dmy3k** [comment]
Hi @Mushoz!

By better supports and stability the following was considered:
- Fixing crashes with latest GNOME releases within shortest possible time.
- Maintaining unit test setup that would help with regressions and generally improve code quality a bit
- Adopting best practices from GNOME extensions team through new releases. GNOME ecosystem evolves pretty fast, IMHO

Having that said, I'm interested to improve extension with my own best effort as I use it on daily basis.

Regarding your issue with profile being enforced continuously. I did fix that in PR you mentioned and happy with how it works. It is included in current project release now, so you can give it a try.

I did close request since I could not reach maintainer(s) for more than a month. So fork was a way to have this and some other minor improvements released. However, the good thing is author of original extension is back and seems to be on track with support.
